# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: warp_wraith
  joint_model_group_pose: calibrate
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - dummy
    - joint_a0
    - joint_a1
    - joint_a2
    - joint_b0
    - joint_b1
    - joint_b2
    - joint_c
    - joint_c0
    - joint_c1
    - joint_c2
    - joint_d0
    - joint_d1
    - joint_d2
    - joint_e0
    - joint_e1
    - joint_e2
    - joint_f0
    - joint_f1
    - joint_f2
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: a_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint_a0
      - joint_a1
      - joint_a2
  - name: b_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint_b0
      - joint_b1
      - joint_b2
  - name: c_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint_c0
      - joint_c1
      - joint_c2
  - name: d_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint_d0
      - joint_d1
      - joint_d2
  - name: e_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint_e0
      - joint_e1
      - joint_e2
  - name: f_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint_f0
      - joint_f1
      - joint_f2
  - name: warp_wraith_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - joint_a0
      - joint_a1
      - joint_a2
      - joint_b0
      - joint_b1
      - joint_b2
      - joint_c0
      - joint_c1
      - joint_c2
      - joint_d0
      - joint_d1
      - joint_d2
      - joint_e0
      - joint_e1
      - joint_e2
      - joint_f0
      - joint_f1
      - joint_f2
  - name: hanger_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      []